### ISSUE TITLE
Comparing two sets of reviews

### ISSUE THREAD

**Issue by MastafaF** [mpoemsl/circe#1]
Hey there, 

Given two corpora of reviews coming from two different sources, I would like to compare the mentions of say a Movie name between two mentioned sources of data. In other words, I want to know how the users refer to a given movie in Corpus 1 and how the users refer to this movie in Corpus 2.  The visualisation in your paper with Usage Graph will also come handy.  Similarly, we could look at some keywords such as 'science fiction' and look at their semantic change across the two corpora. 

Do you think your model can be leveraged to achieve that here? 😄

**Comment by mpoemsl** [comment]
Hey @MastafaF,
not sure if you are referring to this system (CIRCE), since the paper did not feature any visualizations. I think what you describe could be a feasible application of the system, however keep in mind that it primarily makes a prediction about the ranking of change, so the absolute distance between word representations in two corpora will not necessarily be very meaningful.
